name: Android Build

on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_VERSION: 21.4.7075529
      ANDROID_PLATFORM: android-35
      ANDROID_BUILD_TOOLS: 35.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Android SDK
        run: |
          mkdir -p "$ANDROID_HOME" "$HOME/.android"
          echo "### User Sources for Android SDK Manager" > "$HOME/.android/repositories.cfg"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_HOME"
          rm cmdtools.zip
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          mv "$ANDROID_HOME/cmdline-tools"/* "$ANDROID_HOME/cmdline-tools/latest/" || true
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" --licenses
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" --update
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" \
            "platform-tools" \
            "platforms;${ANDROID_PLATFORM}" \
            "build-tools;30.0.3" \
            "build-tools;${ANDROID_BUILD_TOOLS}" \
            "ndk;${ANDROID_NDK_VERSION}" \
            "cmake;3.10.2.4988404"
          cp "$ANDROID_HOME/build-tools/30.0.3/dx" "$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS}/dx" || true
          cp "$ANDROID_HOME/build-tools/30.0.3/lib/dx.jar" "$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS}/lib/dx.jar" || true
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS}" >> $GITHUB_PATH
          echo "$ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_PATH

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon -PdisableGoogleServices=true :TMessagesProj_App:bundleBundleAfat_SDK23Release
          ./gradlew --no-daemon -PdisableGoogleServices=true :TMessagesProj_App:bundleBundleAfatRelease
          ./gradlew --no-daemon -PdisableGoogleServices=true :TMessagesProj_App:assembleAfatStandalone
          ./gradlew --no-daemon -PdisableGoogleServices=true :TMessagesProj_App:assembleAfatRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            TMessagesProj_App/build/outputs/apk/**

      - name: Upload Bundles
        uses: actions/upload-artifact@v4
        with:
          name: bundles
          path: |
            TMessagesProj_App/build/outputs/bundle/**


